### ISSUE TITLE
AttributeError: 'ZoneUpdater' object has no attribute '_current_zone'

### ISSUE THREAD

**Issue by JohnCytron** [JeanDaniel-Fischer/Gandi-Dynamic-Dns#1]
Hello,

I have this python error: `AttributeError: 'ZoneUpdater' object has no attribute '_current_zone'`
When I run `zone_updater.update_zone`
Every value is good. Sorry I don't understand what happened :/

Error message:
```
>>> zone_updater.update_zone(zone_param.get_value(), record_param.get_value(), ipchecker.get_new_ip())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gandi.py", line 61, in update_zone
    self._clone_zone(zone_name)
  File "gandi.py", line 75, in _clone_zone
    if not self._current_zone:
AttributeError: 'ZoneUpdater' object has no attribute '_current_zone'
```

**Comment by JeanDaniel-Fischer** [comment]
Hi,

Does the zone already exist in Gandi ? If it is not the case, you have to create it first. This code only update existing zone. 

"not self._current_zone" is supposed to detect that it is not set and give you a exception with the message:
> Failed to find zone "your zone name"

**Comment by JeanDaniel-Fischer** [comment]
Solve with v1.1.
